
TASKS:
  # 'hlca_small':
  #   input1: data/pp/hlca_small.h5ad
  #   input2: null
  #   label_key: transf_ann_level_3_label
  #   batch_key: study
  #   condition_key: lung_condition_coarse
  #   sample_key: sample
  #   n_splits: 5
  #   methods:
  #     #multigrate: params/hlca_small/multigrate_test.tsv
  #     multigrate: params/hlca_small/multigrate.tsv
  #     pb_rf: params/hlca_small/pb_rf.tsv
  #     pb_nn: params/hlca_small/pb_nn.tsv
  #     gex_nn: params/hlca_small/gex_nn.tsv
  #     gex_rf: params/hlca_small/gex_rf.tsv
  # 'hlca_small_embed':
  #   input1: data/pp/hlca_small_embed.h5ad
  #   input2: null
  #   label_key: transf_ann_level_3_label
  #   batch_key: study
  #   condition_key: lung_condition_coarse
  #   sample_key: sample
  #   n_splits: 5
  #   methods:
  #     # multigrate_mil: params/hlca_small_embed/multigrate_mil_test.tsv
  #     multigrate_mil: params/hlca_small_embed/multigrate_mil.tsv
  #     pb_rf: params/hlca_small_embed/pb_rf.tsv
  #     pb_nn: params/hlca_small_embed/pb_nn.tsv
  #     gex_nn: params/hlca_small_embed/gex_nn.tsv
  #     gex_rf: params/hlca_small_embed/gex_rf.tsv
  'hlca_embed_regions':
    input1: data/pp/hlca_embed_regions.h5ad
    input2: null
    label_key: transf_ann_level_3_label
    batch_key: study
    condition_key: region
    sample_key: sample
    n_splits: 5
    methods:
      # multigrate_mil: params/hlca_embed_regions/multigrate_mil_test.tsv
      multigrate_mil: params/hlca_embed_regions/multigrate_mil.tsv
      pb_rf: params/hlca_embed_regions/pb_rf.tsv
      pb_nn: params/hlca_embed_regions/pb_nn.tsv
      gex_nn: params/hlca_embed_regions/gex_nn.tsv
      gex_rf: params/hlca_embed_regions/gex_rf.tsv
  # 'hlca_healthy_ipf_embed_balanced':
  #   input1: data/pp/hlca_healthy_ipf_embed_balanced.h5ad
  #   input2: null
  #   label_key: transf_ann_level_3_label
  #   batch_key: study
  #   condition_key: lung_condition_coarse
  #   sample_key: sample
  #   n_splits: 5
  #   methods:
  #     # multigrate_mil: params/hlca_healthy_ipf_embed_balanced/multigrate_mil_test.tsv
  #     multigrate_mil: params/hlca_healthy_ipf_embed_balanced/multigrate_mil.tsv
  #     pb_rf: params/hlca_healthy_ipf_embed_balanced/pb_rf.tsv
  #     pb_nn: params/hlca_healthy_ipf_embed_balanced/pb_nn.tsv
  #     gex_nn: params/hlca_healthy_ipf_embed_balanced/gex_nn.tsv
  #     gex_rf: params/hlca_healthy_ipf_embed_balanced/gex_rf.tsv
  'organoid_atlas_subset':
    input1: data/pp/organoid_atlas_subset.h5ad
    input2: null
    label_key: annot_level_2
    batch_key: null
    condition_key: assay_type_differentiation
    sample_key: id
    n_splits: 5
    methods:
      # multigrate_mil: params/organoid_atlas_subset/multigrate_mil_test.tsv
      multigrate_mil: params/organoid_atlas_subset/multigrate_mil.tsv
      pb_rf: params/organoid_atlas_subset/pb_rf.tsv
      pb_nn: params/organoid_atlas_subset/pb_nn.tsv
      gex_nn: params/organoid_atlas_subset/gex_nn.tsv
      gex_rf: params/organoid_atlas_subset/gex_rf.tsv
  # 'hlca_healthy_ipf':
  #   input1: data/pp/hlca_healthy_ipf.h5ad
  #   input2: null
  #   label_key: transf_ann_level_3_label
  #   batch_key: study
  #   condition_key: lung_condition_coarse
  #   sample_key: sample
  #   n_splits: 5
  #   methods:
  #           # multigrate: params/hlca_small/multigrate_test.tsv
  #     multigrate: params/hlca_small/multigrate.tsv
  #     pb_rf: params/hlca_small/pb_rf.tsv
  #     pb_nn: params/hlca_small/pb_nn.tsv
  #     # gex_nn: params/hlca_small/gex_nn.tsv
  #     gex_rf: params/hlca_small/gex_rf.tsv
  'pbmc_healthy_covid':
    input1: data/pp/pbmc_healthy_covid_rna.h5ad
    input2: data/pp/pbmc_healthy_covid_adt.h5ad
    label_key: initial_clustering
    batch_key: Site
    condition_key: Status_on_day_collection_summary
    sample_key: patient_id
    n_splits: 5
    methods:
      # multigrate: params/pbmc_healthy_covid/multigrate_test.tsv
      multigrate: params/pbmc_healthy_covid/multigrate.tsv
      pb_rf: params/pbmc_healthy_covid/pb_rf.tsv
      pb_nn: params/pbmc_healthy_covid/pb_nn.tsv
      gex_nn: params/pbmc_healthy_covid/gex_nn.tsv
      gex_rf: params/pbmc_healthy_covid/gex_rf.tsv
  'hlca_healthy_ipf_balanced':
    input1: data/pp/hlca_healthy_ipf_balanced.h5ad
    input2: null
    label_key: transf_ann_level_3_label
    batch_key: study
    condition_key: lung_condition_coarse
    sample_key: sample
    n_splits: 5
    methods:
      # multigrate_mil: params/hlca_healthy_ipf_balanced/multigrate_test.tsv
      multigrate: params/hlca_healthy_ipf_balanced/multigrate.tsv
      pb_rf: params/hlca_healthy_ipf_balanced/pb_rf.tsv
      pb_nn: params/hlca_healthy_ipf_balanced/pb_nn.tsv
      gex_nn: params/hlca_healthy_ipf_balanced/gex_nn.tsv
      gex_rf: params/hlca_healthy_ipf_balanced/gex_rf.tsv
