
TASKS:
  'hlca_small':
    input: data/hlca_small.h5ad
    label_key: transf_ann_level_3_label
    batch_key: study
    condition_key: lung_condition_coarse
    sample_key: sample
    n_splits: 5
    params: data/params/hlca_small/
    methods:
     # - multigrate
      - pb_rf
     # - pb_nn
     # - gex_nn
    #  - gex_rf
    metrics: null

METHOD_PARAMS:
#   'pb_nn':
#     params: data/params/pb_nn.tsv
#   'gex_nn':
#     params: data/params/gex_nn.tsv
  'pb_rf':
    params: data/params/pb_rf.tsv
#   'gex_rf':
#     params: data/params/gex_rf.tsv