
TASKS:
  'hlca_small':
    input: data/hlca_small.h5ad
    label_key: transf_ann_level_3_label
    batch_key: study
    condition_key: lung_condition_coarse
    sample_key: sample
    n_splits: 5
    methods:
     # - multigrate
      pb_rf: data/params/hlca_small/pb_rf.tsv
     # - pb_nn
     # - gex_nn
      gex_rf: data/params/hlca_small/gex_rf.tsv
