
TASKS:
  # 'hlca_small':
  #   input1: data/hlca_small.h5ad
  #   input2: null
  #   label_key: transf_ann_level_3_label
  #   batch_key: study
  #   condition_key: lung_condition_coarse
  #   sample_key: sample
  #   n_splits: 5
  #   methods:
  #           #  multigrate: params/hlca_small/multigrate_test.tsv
  #       multigrate_mil: params/hlca_small/multigrate_mil_test.tsv
     # multigrate: params/hlca_small/multigrate.tsv
      #pb_rf: params/hlca_small/pb_rf.tsv
      #pb_nn: params/hlca_small/pb_nn.tsv
      #gex_nn: params/hlca_small/gex_nn.tsv
      #gex_rf: params/hlca_small/gex_rf.tsv
  'hlca_small_embed':
    input1: data/hlca_small_embed.h5ad
    input2: null
    label_key: transf_ann_level_3_label
    batch_key: study
    condition_key: lung_condition_coarse
    sample_key: sample
    n_splits: 5
    methods:
      # multigrate_mil: params/hlca_small_embed/multigrate_mil_test.tsv
      multigrate_mil: params/hlca_small_embed/multigrate_mil.tsv
      pb_rf: params/hlca_small_embed/pb_rf.tsv
      pb_nn: params/hlca_small_embed/pb_nn.tsv
      gex_nn: params/hlca_small_embed/gex_nn.tsv
      gex_rf: params/hlca_small_embed/gex_rf.tsv
  'hlca_embed_regions':
    input1: data/hlca_embed_regions.h5ad
    input2: null
    label_key: transf_ann_level_3_label
    batch_key: study
    condition_key: region
    sample_key: sample
    n_splits: 5
    methods:
      # multigrate_mil: params/hlca_embed_regions/multigrate_mil_test.tsv
      multigrate_mil: params/hlca_embed_regions/multigrate_mil.tsv
      pb_rf: params/hlca_embed_regions/pb_rf.tsv
      pb_nn: params/hlca_embed_regions/pb_nn.tsv
      gex_nn: params/hlca_embed_regions/gex_nn.tsv
      gex_rf: params/hlca_embed_regions/gex_rf.tsv
